# ***** LIBRERIAS *****

# Instalamos las librerias que no tenemos y necesitamos
if(!require("ape")) install.packages("ape")
if(!require("BBmisc")) install.packages("cluster")
if(!require("cluster")) install.packages("cluster")
if(!require("corrplot")) install.packages("corrplot")
if(!require("factoextra")) install.packages("factoextra")
if(!require("forecast")) install.packages("forecast")
if(!require("ggplot2")) install.packages("ggplot2")
if(!require("GPArotation")) install.packages("cluster")
if(!require("htmltools")) install.packages("htmltools")
if(!require("htmlwidgets")) install.packages("htmlwidgets")
if(!require("httr")) install.packages("httr")
if(!require("leaflet")) install.packages("leaflet")
if(!require("Metrics")) install.packages("Metrics")
if(!require("MVN")) install.packages("cluster")
if(!require("NbClust")) install.packages("cluster")
if(!require("nFactors")) install.packages("nFactors")
if(!require("plyr")) install.packages("plyr")
if(!require("psych")) install.packages("psych")
if(!require("RColorBrewer")) install.packages("RColorBrewer")
if(!require("readxl")) install.packages("readxl")
if(!require("rgeos")) install.packages("rgeos")
if(!require("spdep")) install.packages("spdep")
if(!require("tmap")) install.packages("tmap")
if(!require("webshot")) install.packages("webshot")

# Cargamos las librerias 
library(ape)           # as.phylo()
library(BBmisc)        # normalize()
library(cluster)       # clusgap()
library(corrplot)      # corrplot()
library(factoextra)    # fviz_nbclust()
library(forecast)      # auto.arima()
library(ggplot2)       # ggplot()
library(GPArotation)   # simplimax()
library(htmltools)     # tags()
library(htmlwidgets)   # saveWidget()
library(httr)          # GET()
library(leaflet)       # leaflet()
library(Metrics)       # rmse()
library(MVN)           # mvn()
library(NbClust)       # NbClust()
library(nFactors)      # parallel()
library(plyr)          # ddply()
library(psych)         # kmo()
library(RColorBrewer)  # brewer.pal()
library(readxl)        # read_excel()
library(rgeos)         # addPolygons()
library(spdep)         # moran()
library(tmap)          # tm()
library(webshot)       # webshot()